import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import './globals.css'

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="scroll-smooth focus:scroll-auto">
      <body
        className={`${poppins.className}  bg-zinc-100 dark:bg-slate-950 dark:text-white text-black`}
      >
        {children}
      </body>
    </html>
  )
}
